### ISSUE TITLE
4.7.0.14 not upgrading on Drobo 5N

### ISSUE THREAD

**Issue by deekayen** [droboports/crashplan#27]
app.log

```
***************************************************************************************************
DateTime     = Sun Nov 20 21:37:55 GMT 2016
OS           = Linux (3.2.58-2, arm)
JVM          = Java(TM) SE Embedded Runtime Environment (1.8.0_06-b23, 32-bit)
Locale       = English (United States), GMT
User         = root, /mnt/DroboFS/Shares/DroboApps/.AppData/crashplan

Application  = CrashPlan
CPVERSION    = 4.7.0 - 1435813200470 (2015-07-02T05:00:00:470+0000) - Build: 344
CPGUID       = 643701973760058442 from file: /var/lib/crashplan/.identity
OrgType      = CONSUMER
WorkingDir   = /mnt/DroboFS/Shares/DroboApps/crashplan/app
LogDir       = /mnt/DroboFS/Shares/DroboApps/crashplan/app/log
AppDataDir   = /mnt/DroboFS/Shares/DroboApps/crashplan/app/conf
CacheDir     = /mnt/DroboFS/Shares/DroboApps/crashplan/app/cache
ArchiveDir   = /mnt/DroboFS/Shares/DroboApps/crashplan/app/backupArchives/
JavaOptions  = [-Dfile.encoding=UTF-8, -Dapp=CrashPlanService, -DappBaseName=CrashPlan, -Xms20m, -Xmx512m, -Dsun.net.inetaddr.ttl=300, -Dnetworkaddress.cache.ttl=300, -Dsun.net.inetaddr.negative.ttl=0, -Dnetworkaddress.cache.negative.ttl=0, -Dc42.native.md5.enabled=false, -Duser.home=/mnt/DroboFS/Shares/DroboApps/.AppData/crashplan, -Djava.io.tmpdir=/mnt/DroboFS/Shares/DroboApps/crashplan/tmp, -Djava.library.path=/mnt/DroboFS/Shares/DroboApps/crashplan/lib, -Djava.net.preferIPv4Stack=true]
Args         = []
LibraryPath  = /mnt/DroboFS/Shares/DroboApps/crashplan/lib:.:lib
ClassPath    = [file:/mnt/DroboFS/Shares/DroboApps/crashplan/app/lib/com.backup42.desktop.jar, file:/mnt/DroboFS/Shares/DroboApps/crashplan/app/lang/]
```

service.log.0

```
[11.20.16 21:37:19.849 INFO  MQ-Peer-3    ervice.peer.PeerVersionValidator] WE have an old version, localVersion=1435813200470 (2015-07-02T05:00:00:470+0000), remoteVersion=1460005200540 (2016-04-07T05:00:00:540+0000), remoteGuid=4200
[11.20.16 21:37:19.852 INFO  MQ-Peer-1    ervice.peer.PeerVersionValidator] WE have an old version, localVersion=1435813200470 (2015-07-02T05:00:00:470+0000), remoteVersion=1460005200540 (2016-04-07T05:00:00:540+0000), remoteGuid=7497247104854324461
[11.20.16 21:37:19.859 INFO  MQ-Peer-3    42.service.history.HistoryLogger] HISTORY:: Downloading a new version of CrashPlan.
[11.20.16 21:37:19.899 INFO  MQ-Peer-3    kup42.service.model.ServiceModel] Saved ServiceModel to disk, 13592 bytes.
[11.20.16 21:37:19.900 INFO  MQ-Peer-3    .service.upgrade.DownloadManager] DownloadManager stopped.
[11.20.16 21:37:19.960 INFO  1816_DwldMgr .service.upgrade.DownloadManager] DOWNLOAD:: Transferring patch at /linux/upgrade/crashplan/1435813200480_323.jar; DownloadManager[patchDir = upgrade, patchFiles = [1435813200480 (2015-07-02T05:00:00:480+0000)], patchProblem = false]
[11.20.16 21:37:19.977 INFO  1816_DwldMgr common.filetransfer.FileTransfer] FT::Client-tid=769957176255459768, guid=4200; START. moduleName=installs, srcPath=/linux/upgrade/crashplan/1435813200480_323.jar, dstPath=upgrade/1435813200480_323.jar, dataWaitTime=900000, options=[]
[11.20.16 21:37:20.066 INFO  MQ-Peer-2    ervice.peer.PeerVersionValidator] WE have an old version, localVersion=1435813200470 (2015-07-02T05:00:00:470+0000), remoteVersion=1435813200480 (2015-07-02T05:00:00:480+0000), remoteGuid=747075570683893912
[11.20.16 21:37:20.096 INFO  MQ-Peer-0      com.code42.backup.BackupEntity] BS[747075570683893912>643701973760058442:: Setting keepBlockState=0 during reset(); BS[747075570683893912>643701973760058442, sameOwner=t, backupConnected=f, authorized=f, usingForBackup=t, backupReady=f, backingUp=f, validating=f, closing=f, keepBlockState=0, con=0, val=0, readyCheckTime=0, MM[BS 747075570683893912>643701973760058442: openCount=0, initialized = true, dataFiles.open = false, /mnt/DroboFS/Shares/DroboApps/crashplan/app/backupArchives/747075570683893912], session=null, syncHandler=null, capacityManager=CapacityManager[747075570683893912>643701973760058442, hostedDestination = false, allotted = -1, allottedForAllRelated = false, lastReset = 0]];
[11.20.16 21:37:20.128 INFO  MQ-Peer-0      com.code42.backup.BackupServer] BS[747075570683893912>643701973760058442:: Informing of backup readiness - ready=true, notReadyCode=NOT_AVAILABLE; BS[747075570683893912>643701973760058442, sameOwner=t, backupConnected=t, authorized=t, usingForBackup=t, backupReady=f, backingUp=f, validating=f, closing=f, keepBlockState=0, con=2016-11-20T21:37:20:097, val=0, readyCheckTime=2016-11-20T21:37:20:097, MM[BS 747075570683893912>643701973760058442: openCount=0, initialized = true, dataFiles.open = false, /mnt/DroboFS/Shares/DroboApps/crashplan/app/backupArchives/747075570683893912], session=RemotePeer-[guid=747075570683893912]; PeerConnectionState-[state=CONNECTED, mode=PRIVATE, currentAddressIndex=0, layer=1/1(Peer::NIO), connecting=2016-11-20T21:37:18:962, connected=2016-11-20T21:37:19:306, attempts=0, connectActivity=2016-11-20T21:37:19:306, keepAliveSent=0, minRetry=32498, reconnectable, location=192.168.0.10:4242, transportPbK=X509.checksum(b55f651d1f150fadee6b214890d6e642), transportPbKRequestable=false, public=50.180.5.10:8154]; Session-[id=769957174577738168, layer=Peer::NIO, closed=false, isAcceptor=false, remoteIdentity=ENDPOINT, completedAuth=true, lat=2016-11-20T21:37:20:079, lrt=2016-11-20T21:37:20:079, lwt=2016-11-20T21:37:19:317, enqueued=true, local=192.168.0.99:48086, remote=192.168.0.10:4242, usingProtos=true, sessionState=NioSessionState[encryptedHeaders=true], LAN], syncHandler=ServerSyncHandler@24593083[ timestamp=0, txValid=false, bmfValid=false, propsValid=false, pathsValid=false, throttler=500/1000], capacityManager=CapacityManager[747075570683893912>643701973760058442, hostedDestination = false, allotted = -1, allottedForAllRelated = false, lastReset = 0]];
[11.20.16 21:37:20.132 INFO  MQ-Peer-0      com.code42.backup.BackupEntity] BS[747075570683893912>643701973760058442:: = Backup ready! (Previously not ready: NOT_AVAILABLE) BackupServerStats@28723903[ BS 747075570683893912>643701973760058442, backupSystemStarted=true, backupNotReadyCode=null, outOfSpace=null, outOfSpaceTimestamp=0, validating=false, backingUp=false, numFilesBackedUp=303032, manifestSize=35069603340, receiveRateInBytesPerSec(B/s)=0.000, sendRateInBytesPerSec(B/s)=0.000, lastBackupTimestamp=Sun Oct 23 23:35:25 GMT 2016, lastCompletedBackupTimestamp=Sat Oct 22 01:55:49 GMT 2016, archiveMaintenanceStats=null, compactStats=CompactStats[lastCompactTimestamp = Mon Nov 14 19:25:04 GMT 2016, numBlocks = 1404997, numBlocksCompleted = 1404997, numBlocksToCompact = 140, numBlocksCompacted = 0, numBlocksFailedChecksum = 0, bytesRemoved = 0, totalBytes = 34902117002, avgBlockSize = 24841, scrapPercent = 0.0%, approxScrapSize = 3477740, scrapPercentAllowed = 0.0, currentInitialBlockNumber = 0, outOfOrderBlocksDetected = false], Session: , sessionSourceBytesCompleted=0 (0.00%), sessionLastSourceBytesCompletedTimestamp=1479677836966, sessionActualBytesSent=0, sessionFilesCompleted=0, sessionStopwatch=3sec, sessionCompletedRateInBytesPerSec(B/s)=0.0, dataSize=34902123146, overhead=167480194, estimatedFreeSpace=-1, minimumFreeSpace=-1, receiveDuration=0 ms; 0MB (0Mbps)]; BS[747075570683893912>643701973760058442, sameOwner=t, backupConnected=t, authorized=t, usingForBackup=t, backupReady=t, backingUp=f, validating=f, closing=f, keepBlockState=0, con=2016-11-20T21:37:20:097, val=0, readyCheckTime=2016-11-20T21:37:20:097, MM[BS 747075570683893912>643701973760058442: openCount=0, initialized = true, dataFiles.open = false, /mnt/DroboFS/Shares/DroboApps/crashplan/app/backupArchives/747075570683893912], session=RemotePeer-[guid=747075570683893912]; PeerConnectionState-[state=CONNECTED, mode=PRIVATE, currentAddressIndex=0, layer=1/1(Peer::NIO), connecting=2016-11-20T21:37:18:962, connected=2016-11-20T21:37:19:306, attempts=0, connectActivity=2016-11-20T21:37:19:306, keepAliveSent=0, minRetry=32498, reconnectable, location=192.168.0.10:4242, transportPbK=X509.checksum(b55f651d1f150fadee6b214890d6e642), transportPbKRequestable=false, public=50.180.5.10:8154]; Session-[id=769957174577738168, layer=Peer::NIO, closed=false, isAcceptor=false, remoteIdentity=ENDPOINT, completedAuth=true, lat=2016-11-20T21:37:20:079, lrt=2016-11-20T21:37:20:079, lwt=2016-11-20T21:37:19:317, enqueued=true, local=192.168.0.99:48086, remote=192.168.0.10:4242, usingProtos=true, sessionState=NioSessionState[encryptedHeaders=true], LAN], syncHandler=ServerSyncHandler@24593083[ timestamp=0, txValid=false, bmfValid=false, propsValid=false, pathsValid=false, throttler=500/1000], capacityManager=CapacityManager[747075570683893912>643701973760058442, hostedDestination = false, allotted = -1, allottedForAllRelated = false, lastReset = 0]];
[11.20.16 21:37:20.153 INFO  MQ-Peer-0    .service.backup.BackupController] BACKUP SOURCE CONNECTED! 643701973760058442 to source 747075570683893912
[11.20.16 21:37:20.365 INFO  main         p42.service.ClientServiceManager] CSM:: -------------------------------------------------------------
[11.20.16 21:37:20.366 INFO  main         p42.service.ClientServiceManager] CSM:: Starting universal services.
[11.20.16 21:37:20.372 INFO  main         kup42.service.GuiceClientRuntime] CMD:: STARTED client runtime in 857.8 μs.
[11.20.16 21:37:20.388 INFO  ice STARTING .code42.service.peer.PeerService] IPeerService STARTED
[11.20.16 21:37:20.393 INFO  main         p42.service.ClientServiceManager] CSM:: Finished starting universal services in 26.16 ms.
[11.20.16 21:37:20.393 INFO  main         p42.service.ClientServiceManager] CSM:: -------------------------------------------------------------
[11.20.16 21:37:20.479 INFO  main         ging.network.nio.NioNetworkLayer] Attempting to listen on 0.0.0.0:4243
[11.20.16 21:37:20.618 WARN  1816_DwldMgr er.FileTransferBlockingRequestor] FT::C-769957176255459768, guid=4200; ; Exception opening output file. java.io.FileNotFoundException: upgrade/1435813200480_323.jar (Permission denied); upgrade/1435813200480_323.jar, 7ms, duration=0 ms; 0MB (0Mbps), waitDuration=0 ms; 0MB (0Mbps), writeDuration=0 ms; 0MB (0Mbps), java.io.FileNotFoundException: upgrade/1435813200480_323.jar (Permission denied)
STACKTRACE:: java.io.FileNotFoundException: upgrade/1435813200480_323.jar (Permission denied)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.code42.io.FileHandle.open(FileHandle.java:67)
	at com.backup42.common.filetransfer.FileTransferBlockingRequestor.<init>(FileTransferBlockingRequestor.java:81)
	at com.backup42.common.filetransfer.FileTransferBlockingRequestorFactory.create(FileTransferBlockingRequestorFactory.java:23)
	at com.backup42.common.filetransfer.FileTransfer.transferFile(FileTransfer.java:355)
	at com.backup42.common.filetransfer.FileTransfer.execute(FileTransfer.java:198)
	at com.backup42.common.filetransfer.FileTransferService.transfer(FileTransferService.java:356)
	at com.backup42.common.filetransfer.FileTransferService.transfer(FileTransferService.java:334)
	at com.backup42.service.CPService.downloadByMessaging(CPService.java:3934)
	at com.backup42.service.upgrade.DownloadManager.downloadPatch(DownloadManager.java:237)
	at com.backup42.service.upgrade.DownloadManager.downloadPatches(DownloadManager.java:181)
	at com.backup42.service.upgrade.DownloadManager.doWork(DownloadManager.java:128)
	at com.code42.utils.AWorker.run(AWorker.java:148)
	at java.lang.Thread.run(Unknown Source)

[11.20.16 21:37:20.621 WARN  1816_DwldMgr .service.upgrade.DownloadManager] DOWNLOAD:: Unable to download patch. url=https://download.crashplan.com/installs/linux/upgrade/crashplan/1435813200480_323.jar?guid=643701973760058442, FileTransferException [srcPath=/linux/upgrade/crashplan/1435813200480_323.jar, errors=[DST_IO_ERROR]]; DownloadManager[patchDir = upgrade, patchFiles = [1435813200480 (2015-07-02T05:00:00:480+0000)], patchProblem = false], FileTransferException [srcPath=/linux/upgrade/crashplan/1435813200480_323.jar, errors=[DST_IO_ERROR]]
STACKTRACE:: FileTransferException [srcPath=/linux/upgrade/crashplan/1435813200480_323.jar, errors=[DST_IO_ERROR]]
	at com.backup42.common.filetransfer.FileTransferBlockingRequestor.<init>(FileTransferBlockingRequestor.java:84)
	at com.backup42.common.filetransfer.FileTransferBlockingRequestorFactory.create(FileTransferBlockingRequestorFactory.java:23)
	at com.backup42.common.filetransfer.FileTransfer.transferFile(FileTransfer.java:355)
	at com.backup42.common.filetransfer.FileTransfer.execute(FileTransfer.java:198)
	at com.backup42.common.filetransfer.FileTransferService.transfer(FileTransferService.java:356)
	at com.backup42.common.filetransfer.FileTransferService.transfer(FileTransferService.java:334)
	at com.backup42.service.CPService.downloadByMessaging(CPService.java:3934)
	at com.backup42.service.upgrade.DownloadManager.downloadPatch(DownloadManager.java:237)
	at com.backup42.service.upgrade.DownloadManager.downloadPatches(DownloadManager.java:181)
	at com.backup42.service.upgrade.DownloadManager.doWork(DownloadManager.java:128)
	at com.code42.utils.AWorker.run(AWorker.java:148)
	at java.lang.Thread.run(Unknown Source)

[11.20.16 21:37:20.622 WARN  1816_DwldMgr 42.service.history.HistoryLogger] HISTORY:: Download of upgrade failed - version 1435813200480, connection lost.
[11.20.16 21:37:20.656 INFO  1816_DwldMgr kup42.service.model.ServiceModel] Saved ServiceModel to disk, 13592 bytes.
```

<img width="563" alt="remote_connection_upgrade_fail_drobo_crashplan" src="https://cloud.githubusercontent.com/assets/382319/20466407/3dfc3238-af41-11e6-8615-177243dafb09.png">

**Comment by ricardopadilha** [comment]
That is perfectly fine. Crashplan's internal update mechanism is too primitive, and breaks the app when it tries to update itself on the Drobo. In fact, the blocking of the self-update mechanism is a feature that was introduced with 4.7.0.14.

With that being said, there won't be a new version of Crashplan for the Drobo anytime soon. The short version is that Crashplan unilaterally broke their client on all ARM devices, and they have no plans of ever supporting ARM devices again. This means no more Crashplan for the Drobo, Raspberry Pi, Synology, QNAP, ReadyNAS, and so on.

For more details, please see:
- http://www.drobospace.com/forums/showthread.php?tid=141634&pid=202265#pid202265
- https://crashplan.setepontos.com/forums/topic/non-intel-cpus-apparently-are-no-longer-supported/
