### ISSUE TITLE
CrashPlan doesn't back up to cloud

### ISSUE THREAD

**Issue by ttop** [droboports/crashplan#9]
With 4.2.0 I can't seem to get CrashPlan on my Drobo 5N to actually back up to CrashPlan central. I have locale, java8 and crashplan successfully installed. I can connect successfully to the Drobo via the CrashPlan UI (running on OSX), I have files configured to back up, but Crashplan is permanently in the state "Waiting for backup" and it says "To do: 0 files" and "Initial backup not complete". The destinations view says the connection status is (for example) "Connected for 7 minutes", but again progress is still "Waiting for backup" which never begins. ressing the "start" arrow doesn't change this status or show any attempt to begin backup. I've tried both scheduled backups and "always on" and neither option results in a backup.

I uninstalled and reinstalled both crashplan and locale and this has made no difference. I'm not sure what further steps I should take for troubleshooting.

**Comment by Lammerink** [comment]
Did you install the latest build/release? My troubles went away with the last one. Try redownloading and installing from https://github.com/droboports/crashplan/releases/tag/v4.2.0

**Comment by ttop** [comment]
Yes, that’s the release which exhibits the behavior I’m talking about. Any suggestions what other steps to take? Is there a log written to disk somewhere I can look at? Are there any preferences stored on the Drobo itself that wouldn’t be removed with uninstalling the app? I’m wondering if there are some settings someplace that are making it not work.

**Comment by Lammerink** [comment]
Open Crashplan and double click on the logo in the top right.
Then type `getlogs` it will return a file path of a zip with all the logs.
Use SSH to copy or move it to a location where you have access to it, for example `/mnt/DroboFS/Shares/DroboApps/crashplan`

**Comment by ttop** [comment]
Here’s what I found in log.txt:

```Exception in thread "W7552768_ScanWrkr" java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.inotify.InotifyManager
	at com.code42.jna.inotify.JNAInotifyFileWatcherDriver.<init>(JNAInotifyFileWatcherDriver.java:21)
	at com.code42.backup.path.BackupSetsManager.initFileWatcherDriver(BackupSetsManager.java:393)
	at com.code42.backup.path.BackupSetsManager.startScheduledFileQueue(BackupSetsManager.java:331)
	at com.code42.backup.path.BackupSetsManager.access$1600(BackupSetsManager.java:66)
	at com.code42.backup.path.BackupSetsManager$ScanWorker.delay(BackupSetsManager.java:1073)
	at com.code42.utils.AWorker.run(AWorker.java:158)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "W27119513_ScanWrkr" java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.inotify.InotifyManager
	at com.code42.jna.inotify.JNAInotifyFileWatcherDriver.<init>(JNAInotifyFileWatcherDriver.java:21)
	at com.code42.backup.path.BackupSetsManager.initFileWatcherDriver(BackupSetsManager.java:393)
	at com.code42.backup.path.BackupSetsManager.startScheduledFileQueue(BackupSetsManager.java:331)
	at com.code42.backup.path.BackupSetsManager.access$1600(BackupSetsManager.java:66)
	at com.code42.backup.path.BackupSetsManager$ScanWorker.delay(BackupSetsManager.java:1073)
	at com.code42.utils.AWorker.run(AWorker.java:158)
	at java.lang.Thread.run(Unknown Source)```

**Comment by Lammerink** [comment]
Please redownload the latest release and install. The release was updated 3 days ago which solves this error.
see issue https://github.com/droboports/crashplan/issues/7

**Comment by ttop** [comment]
Thanks. As you can see, I thought I *had* installed that version, but apparently I was mistaken. I've installed 4.2.0 and this appears to have resolved the issue.
